### ISSUE TITLE
Hotkeys for open and new commands

### ISSUE THREAD

**Issue by ZY-Ang** [CS2103AUG2017-W11-B2/main#79]
Help me update pls :)

**Comment by ZY-Ang** [comment]
Alternatively, do you want to have a constant like `COMMAND_HOTKEY` constant in all the individual commands so developers working on the logic and not the UI can update the hotkeys easily? Like how I created the Set implementation for abbreviations.

**Comment by jo-lyn** [comment]
Sounds good! I'll implement this along with the hotkey update 👍
