### ISSUE TITLE
Make sorting case insensitive

### ISSUE THREAD

**Issue by jo-lyn** [CS2103AUG2017-W11-B2/main#85]
Sorting is currently case-sensitive. Might make more sense for the order to be case insensitive!

**Comment by ZY-Ang** [comment]
@jo-lyn Do you mean the parameters? i.e. n/ N/ etc.?

**Comment by jo-lyn** [comment]
@ZY-Ang For e.g. when sorting "b, A, D" in ascending order, the result is "A, D, b" when it should be "A, b, D"

**Comment by ZY-Ang** [comment]
Ok I get what you mean.

**Comment by ZY-Ang** [comment]
Completed https://github.com/CS2103AUG2017-W11-B2/main/pull/95
